### ISSUE TITLE
TS12-P4 - Design work for P0 UXR Recommendations

### ISSUE THREAD

**Issue by Janeece** [chanzuckerberg/cryoet-data-portal#1198]
P0 UXR recommendations from usability study that are needed before ML Challenge launch
- [UXR Prioritized list](https://docs.google.com/spreadsheets/d/12mXHKCnslg-l0Rjixbra4AHXcY_6vt6JEzjc9fAFqmc/edit?gid=111555811#gid=111555811&fvid=720296411) - this ticket only covers B4 MLC P0 priority items
- [Design stack-ranked list](https://docs.google.com/spreadsheets/d/1ye72cvVIpwzC7nu2ZGsTQAL2zcmuWQ1HM0fqfVplVIs/edit?gid=0#gid=0) - status and details tracked in this sheet

#### Design Tasks:
- [x] Home/Header - Indicate the status of the challenge outside of the challenge page itself.
- [x] Runs table Add a primary button to encourage users to explore a run, and consider alternative designs.
- [x] Make search capabilities clear upfront.
- [x] All Datasets/Depositons - Increase the visibility of the definitions of deposition and dataset.
- [x] Audit and ensure that tables have meaningful empty states. The runs table does not have one. The datasets table needs an improved one to indicate limited search capabilities.

#### Design Consult:
- [x] #1237 
- [x] #1239 
- [x] #1236 

Not included: updating masterfiles to reflect these consult changes, but they are logged in design requsts to pick up later.
