### ISSUE TITLE
Header + Footer + FAQ bugs from bugbash

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#222]
- [ ] when on the browse datasets page, "Browse Data" on the header is not highlighted
- [ ] when on the single run page, "Browse Data" on the header is not highlighted
- [ ] FAQ page code blocks overflow
- [ ] FAQ page does not follow spacing guidelines
- [ ] FAQ page does not have code syntax highlighting

**Comment by manasaV3** [comment]
The title of the page is currently just the link of the site instead of cryoet data portal.

**Comment by junxini** [comment]
clicking on "tools" from the header bar opened the menu to the left:



![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/98626158/a3a83e37-9ff2-4c1d-8bb0-c147bce41a0b)

**Comment by Janeece** [comment]
About and help menu should have a divider between the sections (should be part of SDS component, can ask them to fix if it isnt)

![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/bbd1f4e7-501a-4052-809f-69df117acc98)

**Comment by junxini** [comment]
captured in other tickets
