### ISSUE TITLE
FAQ Page from bugbash

### ISSUE THREAD

**Issue by dgmccart** [chanzuckerberg/cryoet-data-portal#223]
The FAQ page has several styling issues:

- [ ] Links in the intro paragraph are not styled, so users cannot tell what text is a hyperlink. The link to Github issue should be highlighted.
- [x] Links within dropdown are not styled, so users cannot tell what text is a hyperlink.
- [x] Dropdowns for questions are not centered on the copy from the top of the page.
- [x] Code block syntax highlighting
- [x] Add link to data schema in "what is a dataset, run..." and "what is the dataset id..." question
- [x] Paragraph spacing is too small after code blocks (see screenshot below)
- [x] Scrollbar for long code lines (see screenshot below)
<img width="1508" alt="Screenshot 2023-12-06 at 2 26 25 PM" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/92180364/9423ad3d-774d-4f9a-8ede-23dec69adf7f">

- [x] Inline syntax highlighting for code (Dataset, Run,...should have syntax highlighting to indicate that they are referring to python classes)
<img width="765" alt="Screenshot 2023-12-06 at 2 29 01 PM" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/92180364/767e1ac3-0482-41ab-acd7-36de42c2678e">

- [x] Table styling (see screenshot - data should be in a table)
<img width="796" alt="Screenshot 2023-12-06 at 2 30 52 PM" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/92180364/e57c0d31-c906-41e9-93cb-5ebc8f904452">

**Comment by junxini** [comment]
closing this issue, a separate ticket is created to address the last remaining bug from the list above
