### ISSUE TITLE
Website description

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#26]
**User story:** (1.1) I want to see a website description, so that I can understand the purpose of the data portal

**Tasks** 
- [ ] landing page layout
- [ ] landing page image banner
- [ ] #27 (this is added as a separate ticket bc it's a P1)
- [ ] general description (what is the portal)
- [ ] button to direct user to _browse all data_ page
- [ ] Thank you to our data contributors: list of names in alphabetical order

**Link to design:**https://www.figma.com/file/WEmbsjtlBUtRy7pzmuCCjj/CryoET-Data-Portal---Phase-2-Designs?node-id=1929%3A65457&mode=dev

**Comment by manasaV3** [comment]
The content copy will have a placeholder for development.

**Comment by Janeece** [comment]
@kne42 @codemonkey800 here is the image for the header: https://drive.google.com/drive/folders/18Bbmxg_XMMiMngG5P6X0lO_dIThM6iNL?usp=drive_link

There is a jpg version and an png version -- use whichever you prefer. Let me know if there's anything you need me to change about the image export!

For image scaling behavior, as page widens, background should go to black. See here in design: https://www.figma.com/file/WEmbsjtlBUtRy7pzmuCCjj/CryoET-Data-Portal---Phase-2-Designs?type=design&node-id=2777%3A42458&mode=dev

**Comment by Janeece** [comment]
@kne42 @codemonkey800 also, there are a few copy updates in the design:

1. (In Blue section) Update title and copy for browse and download part
![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/1ac20ebe-17ac-40df-a6b1-60d745388d6f)

2. (In blue section) Update copy for contribute data part
![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/c6a6dd5d-7427-4336-9065-fbd19edad06b)

3. Add in header image attribution copy
![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/675f50ce-94b7-43cb-8a6e-81444f93def3)

**Comment by kandarpksk** [comment]
I'm not sure if this is the right place to comment, but it seems like "Grotjahn" is misspelled in two places on the landing page.

**Comment by lauramarcos** [comment]
@kandarpksk just checking your comment in this ticket and in design doc so I wanted to make sure how "Grotjahn" is correctly spelled? thank you!

**Comment by lauramarcos** [comment]
Landing page is working as expected. Thank you!

**Comment by kandarpksk** [comment]
Grotjahn is spelled correctly on the landing page. Thanks!

PS: Sorry for the late reply, I need to figure out getting GitHub notifications by email as I don't look here often.
