### ISSUE TITLE
Publish a release of the Python client package

### ISSUE THREAD

**Issue by andy-sweet** [chanzuckerberg/cryoet-data-portal#278]
# Description

We need a new release of the [Python client package](https://pypi.org/project/cryoet-data-portal/) because the current release (v1.0.1) is incompatible with the production GraphQL schema.

This means that some queries fail. For example

```python
from cryoet_data_portal import Client, Tomogram
client = Client()
tomos = list(Tomogram.find(client))
```

fails with the error

```
TransportQueryError: {'extensions': {'code': 'validation-failed', 'path': '$.selectionSet.tomograms.selectionSet.s3_mrc_scale1'}, 'message': "field 's3_mrc_scale1' not found in type: 'tomograms'"}
```

# Motivation

While some queries work (e.g. `Dataset.find`), once you get to tomograms and annotations (i.e. the important parts), you are likely to run into similar errors.

This issue currently [affects the napari plugin](https://github.com/chanzuckerberg/napari-cryoet-data-portal/issues/18) effectively breaking it.

On [the new website](https://cryoetdataportal.czscience.com/), we also point users to the API and provide ID numbers related to it. Without this release, those instructions are unlikely to be useful.

# Sub-tasks

This task is done when the following are complete.

- [x] The Python package has been updated to reflect the latest GraphQL schema (possibly done in #239).
- [x] The docs and diagrams have been updated appropriately on [the docsite](https://chanzuckerberg.github.io/cryoet-data-portal/index.html).
- [x] A new GitHub release is available with important/breaking changes documented in release notes.
- [x] A new PyPI release has been created and tested.
