### ISSUE TITLE
Design Run Table Annotated Objects filter (Single Dataset page)

### ISSUE THREAD

**Issue by Janeece** [chanzuckerberg/cryoet-data-portal#331]
## Background:

- **User story:** I would like to be able to filter down the list of runs in a single dataset by the annotation objects so that I can only view runs with one or more objects that are relevant to my analysis or ML training needs. 
- **User story**: I would like to be able to set a threshold number of annotated objects in the run so that I know the annotation data in the run has enough quantities relevant to my analysis or ML training needs. 
- In phase 2, we established this filter is not useful without the ability to set a object count threshold, but we didn't have the scope to implement, so design stopped at initial concept (borrowed from CZID)

## Tasks:

- [ ] confirm use cases on this filter
- [ ] refine wording & flesh out behaviors for interacting with this filter. Recommend leveraging patterns from CZID. 
- [ ] Review filter behavior and eng lift
- [ ] Hand-off

## Existing Designs from phase 2:

![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/6788cfd5-8b1b-423b-beb2-8575969078db)

**Figma link for current state of design (1.1-1.3):** https://www.figma.com/file/oUtMvkDdADObFmvOJVVy9G/Phase-2-Deprioritized-Designs-%26-Explorations?type=design&node-id=29%3A11415&mode=design&t=XrAsBnCZPKVmYxZk-1
 Note: use Single Dataset masterfile as page base, not the one that is in this file.

**Comment by Janeece** [comment]
After reviewing the use case with the team, the team felt the previous design was no longer a clear value over just selecting an object name (segmentation masks dont have an object count for example). We decided to just implement the filter as we did on the All datasets page. 

- Spec has been copied into this file: https://www.figma.com/file/oUtMvkDdADObFmvOJVVy9G/Phase-2-Deprioritized-Designs-%26-Explorations?type=design&node-id=133%3A779&mode=design&t=rEDjgxWoOHCx05Zl-1
- Design handed-off in this implementation ticket: https://github.com/chanzuckerberg/cryoet-data-portal/issues/358
