### ISSUE TITLE
Design Annotation Table filters (Single Run Page)

### ISSUE THREAD

**Issue by Janeece** [chanzuckerberg/cryoet-data-portal#332]
## Background:

- **User story:** I would like to be able to filter down a large list of annotations by metadata that is most relevant to my analysis or ML development needs. 
- In phase 2, we established we defined an initial set of filters that we would consider for the annotations table:
  - Method (annotation method)
  - Software (annotation software)
  - Ground Truth Status 
     - value is true/false, 
     - on home page, we use checkbox to only show ground truth (Janeece comment: I'm not convinced that has been the best pattern, you can think about this)
  - Object Name (annotated object name)
      - maybe multi select or threshold
  - GO ID (Object GO ID)
     - likely a search input (user would have a specific ID in mind), but maybe a dropdown with search? 
  - Object Shape Type
     - multi select 
- Filter panel will also need to be added (spec should follow the run and browse all datasets) 
- **Note:** We are currently working on updating the annotations table -- this may impact the filters we'd like to include. Check in with Janeece before starting. 

## Tasks:

- [ ] familiarize yourself with existing filters and annotation metadata (including values)
- [ ] align with team on highest priority filters and any changes to list based on new table designs
- [ ] explore best pattern to use per filter
- [ ] Review with team, get confirmation on implementation scope before fleshing out patterns
- [ ] Hand-off

## Existing Designs from phase 2:

![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/c5b15c13-0b92-45bf-b365-769465f601b0)

**Figma link for current state of design & initial designs (2.1-2.3):** 
https://www.figma.com/file/oUtMvkDdADObFmvOJVVy9G/Phase-2-Deprioritized-Designs-%26-Explorations?type=design&node-id=1%3A32068&mode=design&t=XrAsBnCZPKVmYxZk-1
Note: use masterfile to build off of.
