### ISSUE TITLE
Address frontend TODO comments

### ISSUE THREAD

**Issue by codemonkey800** [chanzuckerberg/cryoet-data-portal#386]
- [ ] [Render author emails + bold style for primary author](https://github.com/chanzuckerberg/cryoet-data-portal/blob/15fd3734675c127a0a602a755378b375dbaf746c/frontend/packages/data-portal/app/components/Run/AnnotationOveriewTable.tsx#L31-L32)
- [ ] [Fix overflow for annotated objects header](https://github.com/chanzuckerberg/cryoet-data-portal/blob/15fd3734675c127a0a602a755378b375dbaf746c/frontend/packages/data-portal/app/components/BrowseData/DatasetTable.tsx#L221)
- [ ] [Fetch frames from API](https://github.com/chanzuckerberg/cryoet-data-portal/blob/15fd3734675c127a0a602a755378b375dbaf746c/frontend/packages/data-portal/app/components/Run/RunHeader.tsx#L96)
- [ ] [Cleanup code for dataset authors](https://github.com/chanzuckerberg/cryoet-data-portal/blob/15fd3734675c127a0a602a755378b375dbaf746c/frontend/packages/data-portal/app/components/Dataset/DatasetAuthors.tsx#L39)
