### ISSUE TITLE
Single run page header area

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#39]
**User story:** (4.1) I want to see high-level description of the run so that I can quickly decide if I would like to investigate further

**Tasks** 
- [ ] count of # of files (Frames, Tilt-series, Tomograms, Annotations)
- [ ] Overview of tilt series, including tilt quality, tilt range, tilt scheme
- [ ] Overview of Tomogram, including resolutions available, tomogram processing, annotated objects 

**Link to design:** https://www.figma.com/file/WEmbsjtlBUtRy7pzmuCCjj/CryoET-Data-Portal---Phase-2-Designs?type=design&node-id=1310%3A11321&mode=dev

**Comment by Janeece** [comment]
Screenshot of design: 

![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/07ca6508-073f-4992-a825-2275abe17eb7)

**Comment by lauramarcos** [comment]
Following bug was raise while working on this ticket:

Count of # of files titles in Single Run page are not in bold [#238](https://github.com/chanzuckerberg/cryoet-data-portal/issues/238)

This is not affecting any functionality so Im moving this ticket forward, thank you!
