### ISSUE TITLE
Annotation table section dividers

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#433]
**Description**: Table section dividers are added to more easily identify which annotations are ground truth

**Tasks:**

- [x] Add 2 section dividers with count: "# Ground Truth Annotations" and "# Other Annotations"
  - "#" represents the total count of annotations in that section (not just what's on the page)
- [x] Section overflows onto the next page (when using pagination), count in dividers should remain the same
- [x] Applying filters will:
  - [x] update the count within the section dividers to reflect
  - [x] ~~hide the section divider if there are no results in that section~~ no longer the case, see below

**Link to design**: https://www.figma.com/design/Kl03vJ6BID3ztPb8B0fsel/Annotation-Table-Updates---Dividers?node-id=1-6108&m=dev

**Comment by manasaV3** [comment]
Here is a sample query for getting some of the basic information for this page:

```
query annotation_table_query($run_id: Int) {
  annotations(order_by: {ground_truth_used: desc, deposition_date: desc}, where: {tomogram_voxel_spacing: {run_id: {_eq: $run_id}}}) {
    id
    ground_truth_status
    deposition_date
    files_aggregate(distinct_on: shape_type) {
      nodes {
        shape_type
      }
    }
    confidence_precision
    confidence_recall
    object_name
    authors(order_by: {author_list_order: asc}) {
      author_list_order
      name
      id
      orcid
    }
  }
  ground_truth_count:annotations_aggregate(where: {tomogram_voxel_spacing: {run_id: {_eq: $run_id}}, ground_truth_status: {_eq: true}}) {    
    aggregate {
      count(columns: id)
    }
  }
  other_annotation_count:annotations_aggregate(where: {tomogram_voxel_spacing: {run_id: {_eq: $run_id}}, ground_truth_status: {_eq: false}}) {    
    aggregate {
      count(columns: id)
    }
  }
}

```

**Comment by junxini** [comment]
> currently blocked, we need backend support to query the ground truth and non-ground truth annotation counts cc: @manasaV3

@manasaV3 Jeremy mentioned there's a backend ticket for this, could you help link when you have a chance?

**Comment by manasaV3** [comment]
@codemonkey800  and @junxini I believe [the query above](https://github.com/chanzuckerberg/cryoet-data-portal/issues/433#issuecomment-1928487300) should help us get the annotation counts by ground_truth_status. If this is related to distinct count by annotation shapes: https://github.com/chanzuckerberg/cryoet-data-portal/issues/582

**Comment by manasaV3** [comment]
This work is now unblocked by this interim solution: https://github.com/chanzuckerberg/cryoet-data-portal/issues/582#issuecomment-2251260752

**Comment by bchu1** [comment]
@Janeece @junxini Here's a run that doesn't have a ground truth annotation: https://frontend.cryoet.staging.si.czi.technology/runs/8413

For runs that have only either ground truth or non-ground truth annotations, should we still display the single divider?

**Comment by junxini** [comment]
> For runs that have only either ground truth or non-ground truth annotations, should we still display the single divider?

good question. i think the majority of runs won't have ground truth annotations. it might not be intuitive for users to see a banner that says "Other annotations" in that context. maybe remove the dividers if the run only has non-ground truths or if it only has ground truths? @Janeece what do you think?

**Comment by Janeece** [comment]
@bchu1 I sycned with @junxini and @kandarpksk and we decided that keeping dividers would be clearest for the user. 

- If a section is empty, show divider, count is 0
- Behavior change: if use applies a filter that causes section to be empty, show divider & count is 0

Design mockup of updated behavior: https://www.figma.com/design/Kl03vJ6BID3ztPb8B0fsel?node-id=1-6108&m=dev#889949041

**Comment by bchu1** [comment]
Copying over from Slack:

> Janeece Pourroy
  10:54 AM
The dividers always show IF if the section is on the page. So if ground truth ends on page 2…
Page 1: only ground truth  divider shows, "other" doesnt start until page 2
Page 2: both dividers now because both sections are on the page
Page 3: only "other" divider shows, "ground truth" ended on page 2
 Examples are on page [1.4 thru 1.6](https://www.figma.com/design/Kl03vJ6BID3ztPb8B0fsel/Annotation-Table-Updates---Dividers?node-id=1-7007&m=dev)
