### ISSUE TITLE
Automate prod release workflow

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/cryoet-data-portal#438]
## Tasks: 

- [ ]  Trigger prod deployment workflow on schedule
- [ ]   Validate checks are passing
    - All tests pass successfully in staging
    - The kill switch allows for a deployment
- [ ]   Get the changelog added and version
- [ ]   Deploy tagged version to prod
- [ ]  Run Tests against prod
