### ISSUE TITLE
Download a single dataset

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#59]
User story: (5.1) I want to download a single dataset, so that I can use it to develop/train ML models

**Tasks:**

P0:
- [ ] download button on single dataset page to open download dataset dialog
- [ ] dialog contains the following elements: title, dataset name, and 2 download tabs for users to chose from 
- [ ] tab 1: download via AWS S3
- _- step 1 asks user to select their save destination (this is optional for user) - P1_ 
- step 2 is a AWS s3 snippet that user can copy
- provide link to AWS instructions 
  - note: instructions are WIP by Dannielle
- [ ] tab 2: download via API
- info box to link user to API documentation
  - link is: https://chanzuckerberg.github.io/cryoet-data-portal/python-api.html
  
P1: 
- [ ] surface dataset ID for user to copy 
- [ ] asks user to select their save destination (this is optional for user)

Link to design: https://www.figma.com/file/WEmbsjtlBUtRy7pzmuCCjj/CryoET-Data-Portal---Phase-2-Designs?type=design&node-id=2315-169422&mode=design&t=8myNEdr3dZigyAP2-0

**Comment by manasaV3** [comment]
Field to referece for source uri: `datasets.s3_prefix`

**Comment by jgadling** [comment]
The download commands will be 

```
aws s3 --no-sign-request sync s3://cryoet-data-portal-public/10000/TS_030/TiltSeries/TS_030.zarr TS_030.zarr
```

**Comment by Janeece** [comment]
Screenshots from design:

AWS tab:
![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/9a223280-e911-4b49-9050-339931f5e499)

API tab:
![Image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/17f1ebf3-8b42-43b5-8794-931e5f72ddc6)

**Comment by lauramarcos** [comment]
Following bugs were found and raised for this ticket:

Dataset # instead of Dataset Name in download single dataset modal [#231](https://github.com/chanzuckerberg/cryoet-data-portal/issues/231)

Download Dataset button is missing the "..." at the end of label [#232](https://github.com/chanzuckerberg/cryoet-data-portal/issues/232)

Able to close "Download Dataset" modal by clicking outside [#233](https://github.com/chanzuckerberg/cryoet-data-portal/issues/233)

"via API" is not in grey when "via AWS S3" is displayed [#234](https://github.com/chanzuckerberg/cryoet-data-portal/issues/234)

Closing and passing thru as non of these issues are critical for Download single dataset functionality although these raised bugs must be tracked and taken over by separate. Thank you!
