### ISSUE TITLE
Multiple Tomograms Epic

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#624]

**Comment by bchu1** [comment]
BE things needed from the final UX mocks:

1. `run.frames`
2. `run.alignments`
3. `alignment.defocus_value`
4. `alignment.is_canonical`
5. `alignment.alignment_type`
6. `alignment.volume_{x|y|z}_dimension`
7. `alignment.volume_{x|y|z}_offset`
8. `alignment.rotation`
9. `alignment.tilt_offset`
10. `alignment.affine_transformation_matrix`
11. `tomogram.alignment`
12. `tomogram.is_portal_standard`
13. `tomogram.is_author_submitted`
14. `tomogram.related_database_entries`
15. `tomogram.publications`
16. `annotation_file.alignment`
17. Download transformed annotation Portal CLI code snippet
18. Download transformed annotation Python API code snippet
19. New S3 directory structure for downloading all `annotation`s of a `run` (or where the new `s3_prefix` is going to live)
20. New download all annotations Python API code snippet

**Comment by manasaV3** [comment]
@junxini Do we have a decision on the `defocus_value` being a P1 feature for the backend?

**Comment by manasaV3** [comment]
@bchu1  This [document spec](https://docs.google.com/document/d/1InjJKrx78Sv44QguMXR0p1o9Y34oPnMOY9J3aj375ks/edit?usp=sharing) should address most of the fields specified in your comment. I will add the ones it doesn't address below:

> 1. run.frames

This  is currently sourced from `tiltseries.frame_count` this can continue to be sourced from there


The python code snippets will be shared out once that has been finalized.

**Comment by junxini** [comment]
> @junxini Do we have a decision on the `defocus_value` being a P1 feature for the backend?

@uermel could you confirm if this is dependent on frames being imported? If so, frames likely won't get in until early Q4

**Comment by bchu1** [comment]
@codemonkey800

The remaining work is all related to the API migration #1101

- [ ] The run header image and View Tomogram button should point to the `isAuthorSubmitted` tomogram. This is blocked by `isAuthorSubmitted`. 
- [ ] The images and View Tomogram buttons in the tomogram table should point to the `isAuthorSubmitted` tomogram. This is blocked on `isAuthorSubmitted`. https://www.figma.com/design/RsjklVi95DFKatU4Uzi2OG/Janeece---Multiple-Tomograms?node-id=998-14910&node-type=instance&m=dev
- [ ] The tomogram table row should display Author Submitted badge with a tooltip on hover when tomogram `isAuthorSubmitted`. There's already a badge component that is used for `isStandardized`. This is blocked by `isAuthorSubmitted`. https://www.figma.com/design/RsjklVi95DFKatU4Uzi2OG/Janeece---Multiple-Tomograms?node-id=998-17700&node-type=instance&m=dev
- [ ] The Alignment column in the tomogram table should show Canonical subtext with a tooltip when alignment `isStandardized`. This is blocked on `isStandardized`. https://www.figma.com/design/RsjklVi95DFKatU4Uzi2OG/Janeece---Multiple-Tomograms?node-id=998-17723&node-type=instance&m=dev
- [ ] The tomogram table should be ordered by first showing `isStandardized` tomograms, then `isAuthorSubmitted` tomograms, then by ID highest to lowest. This is blocked by `isAuthorSubmitted`. https://www.figma.com/design/RsjklVi95DFKatU4Uzi2OG/Janeece---Multiple-Tomograms?node-id=581-9326&node-type=frame&m=dev
- [ ] Alignment ID and Alignment Type in the tomogram sidebar need tooltips. This is not blocked. https://www.figma.com/design/RsjklVi95DFKatU4Uzi2OG/Janeece---Multiple-Tomograms?node-id=1015-20352&node-type=frame&m=dev
- [ ] Tomogram sidebar needs to integrate with `deposition.title`. This is blocked by the name change from `depositionTitle` to `title` not having made it to APIv2 prod yet. https://www.figma.com/design/RsjklVi95DFKatU4Uzi2OG/Janeece---Multiple-Tomograms?node-id=1015-20369&node-type=instance&m=dev
- [ ] Tomogram sidebar needs to integrate with `dataset.datasetPublications`. This is blocked by the name change from `publications` to `datasetPublications` not having made it to APIv2 prod yet. https://www.figma.com/design/RsjklVi95DFKatU4Uzi2OG/Janeece---Multiple-Tomograms?node-id=1015-20365&node-type=instance&m=dev
- [ ] Download tomogram selector needs to also get Author Submitted badge. This is blocked by `isAuthorSubmitted`. https://www.figma.com/design/RsjklVi95DFKatU4Uzi2OG/Janeece---Multiple-Tomograms?node-id=876-26590&node-type=instance&m=dev
- [ ] Download annotation metadata needs to show Alignment ID. This requires migrating the entire `annotations` query to V2 first. This is blocked by `methodLinks` being `null` in APIv2. https://www.figma.com/design/RsjklVi95DFKatU4Uzi2OG/Janeece---Multiple-Tomograms?node-id=1358-15181&node-type=text&m=dev
- [ ] Disabled states and tooltips for unavailable download options. This is not blocked. https://www.figma.com/design/RsjklVi95DFKatU4Uzi2OG/Janeece---Multiple-Tomograms?node-id=417-119499&node-type=rounded_rectangle&m=dev

Here's the final copy spreadsheet: https://docs.google.com/spreadsheets/d/1QEPiDcjGJYWSZXsbRjwHd9aeZjbk_tvv2UQ4DKyMwxk/edit?gid=1179230519#gid=1179230519

Here's a PR I started for migrating the annotations field to V2: https://github.com/chanzuckerberg/cryoet-data-portal/pull/1190

Here's the updated mocks for the download flow now that we're not supporting annotation transformation: https://www.figma.com/design/RsjklVi95DFKatU4Uzi2OG/Janeece---Multiple-Tomograms?node-id=1358-15181&node-type=text&m=dev

**Comment by bchu1** [comment]
Note: `tomogram.is_canonical` in V1 for the intents and purposes of the launch is `tomogram.isAuthorSubmitted` in V2.

**Comment by Janeece** [comment]
@codemonkey800 Here are the prioritized design review comments doc: https://docs.google.com/document/d/1NpMvWUqCvGowvl9MxZP0XlL2qBJBvyB_OJVHl3jqEjE/edit?usp=sharing

Overall this is looking so good (yay @bchu1!), very few P0 comments. If I called out anything that is blocked by the items Bryan listed above, isnt technically feasible, or was previously deprioritized just leave a comment in the doc so I can note it in the designs.
