### ISSUE TITLE
Docs: Eng / Design Improvements for 2024

### ISSUE THREAD

**Issue by dgmccart** [chanzuckerberg/cryoet-data-portal#765]
Running list of design / eng improvements for the docs sites:

**Theme / Figures**
- [x] Update theme to sphinx-immaterial #889([Designs for mkdocs version of this theme](https://www.figma.com/design/Z6uTfpzYfP0h1WENzZTKVJ/Acquire-Documentation-Site?node-id=183-17600&t=YLAGUYDaOnR7ZR5h-1)) 
- [x] Add [data schema graphic](https://github.com/chanzuckerberg/cryoet-data-portal/issues/906) to the site
- [x] Enable dark mode 
- [x] Set up method for changing figures for dark mode
- [x] Specify alignment of figures on the site (e.g. center justified)

**Navigation**
- [x] Add hierarchy to the table of contents (e.g. tutorials landing page with sub-pages) (jump-to-navigation) - break into 2 items
- [x] Fix anchor linking so that the section header isn't cuts off when the hyperlink is clicked) #888 
- [x] Switch hyperlinks to internal links #1109 
- [x] Update link locations on the Portal #1111  
- [x] Function to open accordions from links - needs exploration #772 
- [ ] Accordion / admonition styling
- [x]  Implement cards / tiles design element (e.g. see below) - comes for free from site theme #1188 
<img width="731" alt="Screenshot 2024-05-29 at 2 27 48 PM" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/92180364/0018e630-d2af-4d53-834a-561dd8c8224d">

- [x] Add indicator to the sidebar of where you are when scrolling the page (e.g. see below where the right side bar uses grey or black coloring to indicate where the user is on the page)
<img width="925" alt="Screenshot 2024-05-29 at 2 25 23 PM" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/92180364/fbc04016-8d13-4049-8ea2-cd9d9295cd02">

**API Reference**
- [x] Improve data model graphic (e.g. create an interactive data model graphic) P0 is address [this issue](https://github.com/chanzuckerberg/cryoet-data-portal/issues/180)
- [ ] Custom examples of inherited functions in API documentation #890 - needs exploration
- [x] Improve styling and navigation of API docs following the update to sphinx-immaterial theme
- [ ] ~~Versioned docs~~
- [x] Syntax highlighting in code blocks for python and JSON
- [x] Alphabetize API reference #944

**Comment by dgmccart** [comment]
Start with updating theme, and then move on the API study recommendations related items.
